Coupon API type 값 수정, accessToken 추가
jerome-geek/reactjs-starter pull request #10
Opened 2022-05-12 01:36 UTC by LeeYhunHwan

2022-05-12 08:11 UTC, jerome-geek requested changes

2022-05-12 08:11 UTC, jerome-geek commented on src/api/promotion/coupon.ts
>      issueCoupons: (
coupons보다 coupon이 맞겠죠?

2022-05-12 08:11 UTC, jerome-geek commented on src/api/promotion/coupon.ts
>      getCouponsTarget: (
쿠폰 번호로 타겟상품조회는 쿠폰 번호는 1개, 타겟상품은 N개가 되겠죠?

2022-05-12 08:11 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +            }),
가능한 쿠폰 찾기가 아니고, 상품번호로 발급 가능한 쿠폰 조회면 get이라는 동사를 쓰는게 맞지 않을까요? 형용사는 available보다는 issuable이 맞을 것 같아요

2022-05-12 08:40 UTC, LeeYhunHwan commented on src/api/promotion/coupon.ts
>      issueCoupons: (
설명은 모든 쿠폰이라고 적혀있는데 스키마는 그냥 one depth 객체로 돼 있네요 수정하겠습니다

2022-05-13 02:49 UTC, jerome-geek requested changes

2022-05-13 02:49 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +import { defaultHeaders } from 'api/core';
@LeeYhunHwan 이것만 한 줄로 써주시면 좋을 것 같습니다

2022-05-13 07:15 UTC, merged