SignUpTerms (회원가입 약관)페이지 작성, SignUpInput (회원가입 유저 정보 기입)페이지 작성
jerome-geek/reactjs-starter pull request #17
Opened 2022-05-20 03:23 UTC by LeeYhunHwan

## SignUpTerms
- 전체동의 클릭 시 모든 체크박스 ON/OFF
- 체크박스 클릭 시 체크박스 ON/OFF
- 해당 약관 글자 클릭 시 해당 페이지 이동
- 모든(전체동의 제외) 체크박스 클릭시 전체동의 버튼 ON
- 전체동의 버튼 ON인 경우 체크박스가 하나라도 비동의인 경우 전체동의 버튼 OFF
- 다음 버튼 클릭시 체크박스가 하나라도 클릭이 안된 경우 -> alert: 모든 약관에 동의해주세요
- 다음 버튼 클릭시 회원가입 (유저 정보 기입)페이지로 이동
## SignUpInput
- 이메일, 비밀번호, 자동 등록 방지 유효성 체크
- 이메일 입력 후 중복 됐을시 중복 체크
- 이름, 성별(남성, 여성) radio 버튼
- 생년월일 입력하는 input 박스
- 마케팅 수신 동의 버튼 약관 페이지와 동일 하되 아무것도 체크하지 않아도 회원가입 가능
- 자동 등록 방지 이미지 노출, 자동 등록 방지 code 입력이 가능한 input 박스
- 자동 등록 방지 새로고침 버튼 클릭시 이미지 변경
- 회원가입 클릭시 자동 등록 방지 이미지와 미 일치 시 -> alert: 자동 등록 방지 번호를 확인해주세요

2022-05-24 07:10 UTC, jerome-geek requested changes

2022-05-24 07:10 UTC, jerome-geek commented on src/pages/Member/SignUpInput.tsx
> +    }
interface 부분은 따른 파일로 분리하거나 함수 밖으로 빼는 것이 좋아보이네요

2022-05-24 07:10 UTC, jerome-geek commented on src/pages/Member/SignUpInput.tsx
> +                alert('자동 등록 방지 번호를 확인해주세요');
`res.data` 에 message라는 속성이 있으니 그걸로 표시해주면 더 좋을듯 싶네요

2022-05-24 07:10 UTC, jerome-geek commented on src/pages/Member/SignUpInput.tsx
> +        return false;
여기에 false를 추가하면 then/catch에 상관없이 false가 리턴될텐데 확인하셨을까요?

2022-05-24 07:10 UTC, jerome-geek commented on src/pages/Member/SignUpInput.tsx
> +import { SEX, TERM } from 'api/member/profile';
해당 enum은 `src/api/member/profile` -> `src/react-app-env.d.ts`로 옮기는 것이 좋을 것 같네요

2022-05-24 07:10 UTC, jerome-geek commented on src/pages/Member/SignUpInput.tsx
> +                code: captchaCode.current?.value || '',
여기도 굳이 default value로 빈 string을 넣은 이유가 있을까요?

2022-05-25 01:12 UTC, LeeYhunHwan commented on src/pages/Member/SignUpInput.tsx
> +import { SEX, TERM } from 'api/member/profile';
enum 은 env.d.ts에서 생성 후 외부에서 사용시 에러가 일어나는데 혹시 제가 잘못 알고 있는건가요?

2022-05-25 01:16 UTC, LeeYhunHwan commented on src/pages/Member/SignUpInput.tsx
> +import { SEX, TERM } from 'api/member/profile';
아 models로 빼라는 말씀인가요?

2022-05-26 02:06 UTC, LeeYhunHwan commented on src/pages/Member/SignUpInput.tsx
> +    }
일단은 빼두고 나중에 다른 별도의 파일로 나누는게 더 이쁠거 같습니다

2022-05-26 02:53 UTC, jerome-geek commented on src/pages/Member/SignUpInput.tsx
> +import { SEX, TERM } from 'api/member/profile';
@georg

2022-05-26 07:01 UTC, jerome-geek approved these changes

2022-05-26 07:01 UTC, merged