shopAPI >  promotion > coupon API 추가
jerome-geek/reactjs-starter pull request #2
Opened 2022-05-03 02:35 UTC by LeeYhunHwan

모든 api에 accessToken 혹은 eventNo 등이 필요해서 주석처리를 따로 하진 않았습니다.

2022-05-03 05:08 UTC, jerome-geek commented on src/api/coupon/index.ts
> +import request from '../core';
Library와 파일은 한 줄 띄어서 import하면 좋을 것 같아요, request import도 상대경로가 아니고 baseUrl 적용해서 import하면 보기 더 깔끔할 것 같네요

2022-05-03 05:08 UTC, jerome-geek commented on src/api/coupon/index.ts
> +            url: `/coupons/products/${productNo}/issable/coupons`,
오타 수정해주세요!

2022-05-03 05:08 UTC, jerome-geek commented on src/api/coupon/index.ts
> +        }),
여긴 왜 url이 똑같을까요? 다시 한 번 확인해주세요

2022-05-04 05:15 UTC, jerome-geek commented on src/api/coupon/index.ts
> +    postCouponsDownload: (couponNo: String): Promise<AxiosResponse> =>
@LeeYhunHwan  post라는 동사는 해당 API가 하는 역할을 잘 설명해주지 못하는 것 같은데 어떻게 생각하시나요?

2022-05-05 10:59 UTC, jerome-geek requested changes

2022-05-05 10:59 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +    issuePromotionCoupons: (promotionCode: String): Promise<AxiosResponse> =>
API 설명을 읽어보니 이건 쿠폰 하나만 발급되는데 coupons라고 쓰면 헷갈릴 수 있지 않을까요?

2022-05-05 10:59 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +        pageSize: 10,
default Parameter는 `=` 연산자를 사용하는 것으로 알고 있는데 `:` 연산자는 왜 사용하신걸까요?

2022-05-05 10:59 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +    issueEventsCoupons: (eventNo: String): Promise<AxiosResponse> =>
API 설명에 따르면 events 보다는 event가 더 맞을 것 같은데 어떻게 생각하시나요?

2022-05-05 10:59 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +
POST 요청에 body가 빠졌네요

2022-05-05 10:59 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +    getCouponsProductsIssuable: (
함수명이 해석이 안되네요, 그냥 단어를 순서대로 붙인 느낌이라 함수명을 더 고민해보셔야 할 것 같아요

2022-05-05 10:59 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +            data: { channelType },
parameter가 빠졌네요, 다시 한 번 확인해주세요

2022-05-07 03:30 UTC, jerome-geek requested changes

2022-05-07 03:30 UTC, jerome-geek commented on .env
> +REACT_APP_CLIENT_ID=f7IuuZPHwmc7hGfGmbhHog==
`.env` 파일은 커밋 하면 안되는거 아시죠?

2022-05-07 03:30 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +    ): Promise<AxiosResponse> =>
GET 요청의 queryString이나 POST 요청의 Body는 객체 형태로 작성해주시면 좋을 것 같아요

2022-05-07 03:30 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +        request({ method: 'GET', url: '/coupons/summary', data: expireDay }),
GET 요청의 queryString이나 POST 요청의 Body는 객체 형태로 작성해주시면 좋을 것 같아요

2022-05-07 03:30 UTC, jerome-geek commented on src/api/promotion/coupon.ts
> +    issuePromotionCoupon: (promotionCode: String): Promise<AxiosResponse> =>
GET 요청의 queryString이나 POST 요청의 Body는 객체 형태로 작성해주시면 좋을 것 같아요
+ 등록된 프로모션 코드를 이용해 쿠폰을 발급받는 API니까 함수명을 issueCouponByPromotionCode 쓰면 좋을 것 같은데 어떻게 생각하시나요?

2022-05-09 00:21 UTC, LeeYhunHwan commented on .env
> +REACT_APP_CLIENT_ID=f7IuuZPHwmc7hGfGmbhHog==
죄송합니다 다음부턴 올리지 않겠습니다.

2022-05-09 00:21 UTC, LeeYhunHwan commented on src/api/promotion/coupon.ts
> +    issuePromotionCoupon: (promotionCode: String): Promise<AxiosResponse> =>
너무 긴거 같아서 줄여 보려고 했는데 알아보지 못하면 줄인 의미가 없다고 생각이 드네요, 그렇게 바꾸겠습니다.

2022-05-09 00:41 UTC, LeeYhunHwan commented on src/api/promotion/coupon.ts
> +        request({ method: 'GET', url: '/coupons/summary', data: expireDay }),
GET 요청의 header 값 까지 포함해서 말인가요?

2022-05-09 05:52 UTC, merged