shop API > order > cart API 작성
jerome-geek/reactjs-starter pull request #22
Opened 2022-05-26 07:30 UTC by LeeYhunHwan

## cart
- 장바구니 가져오기 (getCart)
- 장바구니 수정하기 (updateCart)
- 장바구니 등록하기 (registerCart)
- 장바구니 삭제하기 (deleteCart)
- 장바구니에서 선택된 상품금액 계산하기 (getSelectedCartPrice)
- 장바구니 개수 가져오기 (getCartCount)
- 장바구니에서 선택된 항목만 장바구니 그룹별로 재계산하기 (getSelectedCartGroupPrice)
- 장바구니 저장 상품 유효성 체크하기 (getCartValidation)

2022-05-26 09:00 UTC, jerome-geek requested changes

2022-05-26 09:00 UTC, jerome-geek commented on src/api/order/cart.ts
> +    getCartValidation: (): Promise<AxiosResponse> =>
get보다는 check가 좋을 것 같은데 어떻게 생각하세요?

2022-05-26 09:03 UTC, LeeYhunHwan commented on src/api/order/cart.ts
> +    getCartValidation: (): Promise<AxiosResponse> =>
저번에도 말씀하셨던거 같은데 제가 같은 실수를 했네요 check로 수정하겠습니다.

2022-05-27 05:28 UTC, jerome-geek approved these changes

2022-05-27 05:28 UTC, merged