shop API > claim > guest API 작성
jerome-geek/reactjs-starter pull request #25
Opened 2022-05-30 06:39 UTC by LeeYhunHwan

## guest
- 옵션취소 신청하기(복수옵션) (cancelPendingDepositOrder)
- 클레임시 변경되는 주문 환불 예상금액 계산하기(복수옵션) (getRefundPrice)
- 반품 신청하기(복수옵션) (requestReturn)
- 환불 계좌 정보 수정하기 (updateReturnAccount)
- 클레임 철회시 유효성 검증 타입 조회하기 (checkCancelOfClaimValidation)
- 클레임 상세보기(클레임 번호) (getClaimDetailByClaimNo)
-  클레임 철회하기(클레임 번호) (cancelClaimByClaimNo)
- 클레임 신청을 위한 정보 조회하기 (getClaimInformation)
- 옵션취소 신청하기 (cancelClaimOption)
- 클레임시 변경되는 주문 황불금액 계산하기(단일옵션) (getClaimOptionPrice)
- [alpha 개발 중] 교환 신청하기 (requestExchange)
- 클레임 상세보기(주문상품 옵션번호) (getClaimDetailByOptionNo)
- 반품 신청하기(단일옵션) (requestReturnOption)
- 클레임 철회하기(주문상품 옵션번호) (cancelClaimByOrderNo)
- 주문취소 신청하기 (cancelOrder)

2022-05-30 16:06 UTC, jerome-geek requested changes

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +    checkCancelOfClaimValidation: (claimNo: string): Promise<AxiosResponse> =>
이 API는 checkClaimValidation이 더 나아보이는데 어떻게 생각하시나요? 
설명은 `클레임 철회시` 라고 써놨지만 사실 필요없는 문구 같아보이네요

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +        }),
`클레임 목록을 조회하는 비회원용 API입니다.` 클레임 목록을 조회하는 API라고 나와있는데, 리턴값 스키마는 object 형식이네요. 이 부분인 향후에 어떤 리턴값이 오는지 확인이 필요할 것 같아요

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +            }),
`옵션취소 신청하기` 라는 API 인데 동사가 cancel 보다는 request라는 동사를 써주는게 더 의미가 명확할 듯 싶네요
샵바이는 아직 전체적으로 파악이 되지 않았지만, 고도몰 같은 경우에는 취소 / 교환 / 반품 같은 경우에는 관리자의 승인이 있어야 하기 때문에 바로 처리가 되지 않기 때문입니다.(아마 샵바이도 비슷할 듯 싶네요)

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +    requestExchange: (
여긴 request라고 잘 써놓으셨네요

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +    requestReturnOption: (
단일 옵션 반품 신청은 requestReturnOfSingleOption,
복수 옵션 반품 신청은 requestReturnOfMultipleOptions
정도로 구분하면 좋을 듯 싶은데 더 좋은 생각이 있으신가요?
(함수명이 조금 길긴 하지만, 역할을 더 명확하게 표시할 수 있을 것 같아서요)

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +    cancelClaimByOrderNo: (orderOptionNo: string): Promise<AxiosResponse> =>
파라미터를 orderOptionNo니까 cancelClaimByOrderOptionNo가 더 나을 것 같은데 너무 길어보여서 이렇게 바꾸신걸까요?

2022-05-30 16:06 UTC, jerome-geek commented on src/api/claim/guest.ts
> +    cancelOrder: (
여기도 cancel보다는 request를 이용해서 더 명확하게 역할을 나타내주면 좋을 것 같으니,
cancelOrder보다는 requestCancel가 더 낫지 않을까요?

2022-05-31 01:41 UTC, LeeYhunHwan commented on src/api/claim/guest.ts
> +        }),
제 생각엔 클레임 신청을 위한 목록들을 불러오는 api 같은데 이름이 마땅한게 떠오르지 않았습니다.

2022-05-31 01:42 UTC, LeeYhunHwan commented on src/api/claim/guest.ts
> +            }),
아 알겠습니다 감사합니다

2022-05-31 01:51 UTC, LeeYhunHwan commented on src/api/claim/guest.ts
> +    cancelClaimByOrderNo: (orderOptionNo: string): Promise<AxiosResponse> =>
네 너무 길어서 OrderNo 만 사용했는데, 그래도 orderOptionNo를 사용하니까 cancelClaimByOrderOptionNo 맞을거 같기도 합니다.
항상 긴 이름과 정확한 뜻 사이에서 고민이 되네요

2022-05-31 07:58 UTC, jerome-geek commented on src/api/claim/guest.ts
> +        }),
이 부분은 향후에 더 논의가 필요할 것 같습니다

2022-06-02 04:11 UTC, jerome-geek approved these changes

2022-06-02 04:11 UTC, merged