:sparkles: feat: shop API > order > shippingAddress 작성
jerome-geek/reactjs-starter pull request #28
Opened 2022-05-31 05:03 UTC by LeeYhunHwan

## shippingAddress
- 배송지 목록 가져오기 (getShippingAddressList)
- 배송지 등록하기 (registerShippingAddress)
- 최근 배송지 가져오기 (getRecentShippingAddress)
- 배송지 가져오기 (getShippingAddress)
- 배송지 수정하기 (updateShippingAddress)
- 배송지 삭제하기 (deleteShippingAddress)
- 기본 배송지 수정하기 (changeShippingAddressToDefault)

2022-06-01 03:43 UTC, jerome-geek requested changes

2022-06-01 03:43 UTC, jerome-geek commented on src/api/order/shippingAddress.ts
> +    changeShippingAddressToDefault: (
해당 함수명은 change라는 동사를 쓰는 것보다 update 동사를 써서 `updateDefaultShippingAddress`가 조금 더 나아보이는데 어떻게 생각하시나요?

2022-06-02 04:44 UTC, LeeYhunHwan commented on src/api/order/shippingAddress.ts
> +    changeShippingAddressToDefault: (
제가 작성한 이름보다 제롬님이 지어준 이름이 훨씬 낫네요

2022-06-02 05:13 UTC, jerome-geek approved these changes

2022-06-02 05:13 UTC, merged