shopAPI > product > Display API  추가
jerome-geek/reactjs-starter pull request #3
Opened 2022-05-03 04:52 UTC by LeeYhunHwan

get display brands 브랜드 목록 조회하기
get display brands {brandNo} 브랜드 상세 조회하기

2022-05-05 11:17 UTC, jerome-geek requested changes
전체적으로 빠진 부분이 조금 있네요, API 문서 천천히 읽으시면서 처음부터 다시 확인해보시면 좋겠네요

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/display.ts
> +        sort,
default parameter가 빠져있네요

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/display.ts
> +    sort?: { criterion: String; direction: String };
sort안에 criterion, direction은 String으로 선언하는 것보다 enum 타입으로 타입을 강제해주는 게 좋을 것 같아요

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/display.ts
> +    getDisplayBrandsDetail: (brandNo: String): Promise<AxiosResponse> =>
여기도 함수명이 적정하지 않은 것 같네요, brand가 복수형이라면 여러 브랜드의 정보를 조회해야되는데 API와 맞지 않는 것 같네요

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/index.ts
> +import product from './product';
여기도 상대경로로 쓰는 것보다 baseUrl을 사용해서 작성하는게 일관성있는 코드가 될 것 같은데 어떻게 생각하시나요?

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/product.ts
> +        productSort,
default parameter가 빠졌네요

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/product.ts
> +}
API 문서를 참고해보면 nullable이라고 써져있는데, 이러면 type에 null도 추가해주는 것이 좋겠죠?

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/product.ts
> +        pageNumbewr,
오타 수정해주세요, vscode extension 중에 Code Spell Checker가 있는데 이거 설치해서 spelling 체크를 하시면 더 좋겠네요

2022-05-05 11:17 UTC, jerome-geek commented on src/api/product/product.ts
> +    ): Promise<AxiosResponse> =>
Parameter는 객체 형식으로 묶어주시고, default parameter가 빠졌고,nullable이니 type에 null도 추가해주시고, salesStatus는 enum형식으로 관리하면 좋겠네요

2022-05-05 13:42 UTC, LeeYhunHwan commented on src/api/product/product.ts
> +        pageNumbewr,
정말 좋은 툴이네요

2022-05-10 15:25 UTC, jerome-geek commented
Description 다시 작성해주세요

2022-05-12 02:42 UTC, jerome-geek requested changes

2022-05-12 02:42 UTC, jerome-geek commented on src/api/product/product.ts
> +    getProductsUrl: (productNo: string): Promise<AxiosResponse> =>
여러 상품의 url을 가져오는게 아니니까 products -> product 단수로 변경하는 것이 좋겠죠?
+ 그냥 url이 아니고 단축 url 이라는 것을 명시하면 더 좋을 것 같은데 어떻게 생각하세요?

2022-05-12 02:42 UTC, jerome-geek commented on src/api/product/product.ts
> +    getOptionsImages: (
특정 옵션의 이미지를 조회하는 것 같은데 options를 복수로 쓰면 안되지 않을까요?

2022-05-12 02:42 UTC, jerome-geek commented on src/api/product/product.ts
> +    groupManagementCodeInquiry: ({
여기도 동사가 빠졌네요

2022-05-12 02:42 UTC, jerome-geek commented on src/api/product/product.ts
> +    getProductOption: (productNo: string): Promise<AxiosResponse> =>
한 상품에 옵션이 여러개가 있을 수 있으니 options가 낫겠죠? 실제로 response도 배열형태로 오는 것 같네요

2022-05-12 07:52 UTC, jerome-geek commented on src/api/product/product.ts
> +    getProductsUrl: (productNo: string): Promise<AxiosResponse> =>
@LeeYhunHwan 이건 왜 함수명을 `getProductUrls` 로 바꾸신걸까요?

2022-05-12 07:56 UTC, LeeYhunHwan commented on src/api/product/product.ts
> +    getProductsUrl: (productNo: string): Promise<AxiosResponse> =>
이상하게 수정을 했네요 다시 제대로 수정하겠습니다.

2022-05-13 02:37 UTC, merged