shop API > order > wish API 작성
jerome-geek/reactjs-starter pull request #30
Opened 2022-05-31 08:50 UTC by LeeYhunHwan

## wish
- 위시리스트 리스트 가져오기 (getWishList)
- 위시리스트 수정하기 (updateWishList)
- 위시리스트 등록하기 (writeWishList)
- 위시리스트 삭제하기 (deleteWishList)
- 위시리스트 개수 가져오기 (getWishListCount)

2022-06-01 03:41 UTC, jerome-geek requested changes

2022-06-01 03:41 UTC, jerome-geek commented on src/api/order/wish.ts
> +        }),
method는 코드를 위해 대문자로 작성해주시는게 통일성있는 코드가 될 것 같네요
그리고 wishNos라는 파라미터는 comma seperated value인데 number형식이 comma로 구분되어 들어가면 될 것 같네요.
그럼 결국에는 string이 될텐데, 샵바이에서 이렇게 쓰이는 타입이 많으니 generic을 사용해서 이 타입을 만들어보면 어떨까요?

2022-06-02 01:21 UTC, LeeYhunHwan commented on src/api/order/wish.ts
> +        }),
generic보다는 literal을 이용해서 만들려고는 했는데 최대 개수가 몇 개인지 모르는 상태에선 작성이 힘들지 않을까 해서 일단 작성을 하지 않고 문서에 적혀있는 type인 number로 했습니다.
generic은 제가 아직 미숙해서 잘 못하지만 잘 찾아보고 해보겠습니다.

2022-06-02 02:27 UTC, jerome-geek commented on src/api/order/wish.ts
> +        }),
literal로 만들때 generic으로 타입을 주입받고 갯수도 동적으로 만드는 방법이 없을까요?
저도 확실히 이게 가능한지 몰라서 조금 더 고민해보고 이야기해보면 좋을 듯 싶네요

2022-06-02 04:01 UTC, jerome-geek approved these changes

2022-06-02 04:01 UTC, jerome-geek commented on src/App.tsx
> +// import Login from 'pages/Member/Login';
여긴 왜 주석처리하신걸까요?

2022-06-02 04:48 UTC, LeeYhunHwan commented on src/App.tsx
> +// import Login from 'pages/Member/Login';
실수로 올렸습니다.
그리고 주석처리는 제 app.tsx 파일에 Login 컴포넌트가 두 개나 import 돼 있어서 오류를 일으켜서 주석처리를 했습니다.

2022-06-03 04:37 UTC, merged