shopAPI > claim > member API 작성
jerome-geek/reactjs-starter pull request #32
Opened 2022-06-02 08:22 UTC by LeeYhunHwan

## member
- 회원 클레임 목록 조회하기 (getClaimList)
- 회원 옵션취소 신청하기(복수옵션) (requestCancelOptions)
- 회원 클레임시 변경되는 주문의 환불 예상금액 계산하기 (getRefundPrice)
- 회원 반품 신청하기(복수옵션) (requestReturnOfMultipleOptions)
- 회원 환불 계좌 정보 수정하기 (updateReturnAccount)
- 회원 클레임 철회시 유효성 검증 타입 조회하기 (checkClaimValidation)
- 회원 클레임 상세보기(클레임 번호) (getClaimDetailByClaimNo)
- 회원 클레임 철회하기(클레임 번호) (cancelClaimByClaimNo)
- 회원 클레임 신청을 위한 정보 조회하기 (getContentsForClaim)
- 회원 옵션취소 신청하기(단일옵션) (requestCancelClaimOption)
- 회원 클레임시 변경되는 주문의 환불 예상금액 계산하기(단일옵션) (getClaimOptionPrice)
- 회원 클레임 교환 신청하기 (requestExchange)
- 회원 클레임 상세보기(주문상품 옵션번호) (getClaimDetailByOptionNo)
- 회원 반품 신청하기(단일옵션) (requestReturnOfSingleOption)
- 회원 클레임 철회하기(주문상품 옵션번호) (cancelClaimByOrderOptionNo)
- 회원 주문취소 신청하기 (requestCancel)

2022-06-03 05:13 UTC, jerome-geek requested changes

2022-06-03 05:13 UTC, jerome-geek commented on src/api/claim/member.ts
> +        SearchDate & { claimTypes: CLAIM_TYPE }): Promise<AxiosResponse> =>
claimTypes는 null인 경우 전체리스트를 가져오니 nullable로 만들어주면 좋겠네요

2022-06-03 05:13 UTC, jerome-geek commented on src/api/claim/member.ts
> +        },
이건 왜 이렇게 쓰셨을까요? params/data에 들어가는 값만 object형태로 전달하기로 하지 않았나요? 혹시 제가 잘못 기억하고 있는 부분이 있으면 알려주세요

2022-06-03 05:13 UTC, jerome-geek commented on src/api/claim/member.ts
> +    }): Promise<AxiosResponse> =>
여기도 위와 마찬가지입니다

2022-06-03 05:13 UTC, jerome-geek commented on src/api/claim/member.ts
> +        }),
여기는 orderOptionNo로 조회하는 값인데 함수명에 optionNo라고 쓰셨고, 밑에 cancelClaimByOrderOptionNo는 orderOptionNo로 썼는데 통일이 필요해보이네요

2022-06-03 05:13 UTC, jerome-geek commented on src/api/claim/member.ts
> +        },
여기도 orderOptionNo를 왜 이렇게 쓰셨을까요? url에 들어가는 값들은 확인이 필요해보이네요

2022-06-03 05:43 UTC, LeeYhunHwan commented on src/api/claim/member.ts
> +        },
제가 착각했네요 확인하고 수정하겠습니다.

2022-06-04 02:38 UTC, jerome-geek commented on src/api/claim/member.ts
> +        SearchDate & { claimTypes: CLAIM_TYPE }): Promise<AxiosResponse> =>
optional이 아니고 값을 null로 명시적으로 전달해야하는데 optional로 쓰면 안될 것 같지 않나요?

2022-06-07 02:06 UTC, LeeYhunHwan commented on src/api/claim/member.ts
> +        SearchDate & { claimTypes: CLAIM_TYPE }): Promise<AxiosResponse> =>
어 이런 형식에 대해서 저번에 대화 한것 같은데, nullalbe한 값들은 해당 파라미터를 따로 null로 보내주지 않아도 값이 제대로 나오는 것을 확인 가능합니다.

2022-06-07 06:02 UTC, jerome-geek approved these changes

2022-06-07 06:02 UTC, merged