자주 묻는 질문(Faq) page 작성
jerome-geek/reactjs-starter pull request #48
Opened 2022-06-22 02:04 UTC by LeeYhunHwan

2022-06-22 02:56 UTC, jerome-geek requested changes

2022-06-22 02:56 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +    );
검색은 따로 분리하지 않고 여기서 처리할 수 있을 것 같네요

2022-06-22 02:56 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +        useState<{ [id: string]: (BoardListItem & { content?: string })[] }>();
여기서 데이터 type은 밑에서도 사용하니 generic을 이용해서 key / value로 된 데이터 타입을 만들어서 쓰면 좋을 듯 싶네요

2022-06-22 02:56 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +                                    : ''
삼항연산자보다는 &&를 사용해서 작성해주세요

2022-06-22 02:56 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +                            id={`${categoryNo}`}
template literal이 필요없는 부분인 것 같네요

2022-06-22 02:56 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +    const [faqList, setFaqList] = useState<BoardCategory[]>([]);
변수명만 봐서는 헷갈릴 수 있겠네요

2022-06-22 02:56 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +                                            }
DetailBox가 클릭될때마다 매번 API가 호출되는게 맞을까요?

2022-06-22 06:12 UTC, LeeYhunHwan commented on src/pages/Etc/Faq.tsx
> +                                    : ''
className안을 아예 비워 둘 수가 없어 ''처리를 해줬습니다. 혹시 && 연산자나 혹은 더 단순한 방법이 있을까요?

2022-06-22 06:12 UTC, LeeYhunHwan commented on src/pages/Etc/Faq.tsx
> +                            id={`${categoryNo}`}
id자체가 필요하지 않아 일단 삭제했습니다.

2022-06-27 06:54 UTC, jerome-geek requested changes

2022-06-27 06:54 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +    }));
useTypedSelector를 쓸때는 shallowEqual을 같이 써주세요

2022-06-27 06:54 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +                                    : ''
isActive props에 true / false를 넣어주는 방향으로 하면 더 좋을 것 같아요

2022-06-27 06:54 UTC, jerome-geek commented on src/pages/Etc/Faq.tsx
> +    };
state값 세팅할때 useRef안써도 되겠죠?

2022-06-28 01:31 UTC, jerome-geek commented
refetch 때문에 isFetching으로 잘 변경해주셨네요

2022-06-28 01:31 UTC, jerome-geek approved these changes

2022-06-28 01:31 UTC, merged