ProductList page 작성
jerome-geek/reactjs-starter pull request #51
Opened 2022-06-29 04:58 UTC by LeeYhunHwan

2022-06-29 07:23 UTC, jerome-geek requested changes

2022-06-29 07:23 UTC, jerome-geek commented on src/api/product/product.ts
> +export interface ProductResponse {
이 부분은 model로 빼주셔야할 것 같습니다

2022-06-29 07:23 UTC, jerome-geek commented on src/pages/Product/ProductList.tsx
> +    };
여기 배열도 destructuring 해주는게 index를 쓰는 것보단 더 명시적인 코드가 될 것 같네요

2022-06-29 07:23 UTC, jerome-geek commented on src/pages/Product/ProductList.tsx
> +    }, [categoryNo]);
currentCategroyNo와 secondaryCategory를 구분해놓은 이유는 무엇일까요? categoryNo 같은 경우에는 parameter로 받아와서 처음 카테고리 정보를 부를때 빼고는 쓰이지 않는 것 같은데, 굳이 state로 관리할 필요가 있나요?

2022-06-29 07:23 UTC, jerome-geek commented on src/pages/Product/ProductList.tsx
> +                categoryNos: secondaryCategory?.toString(),
이미 state에 string이라고 선언해놓았는데, 여기서도 `toString` method가 필요할까요?
제가 생각하기엔 API에서는 number로 사용되니, state는 number로 통일하고 API를 호출할때만 형변환하면 더 좋을 것 같은데 어떻게 생각하세요?

2022-06-29 08:19 UTC, LeeYhunHwan commented on src/pages/Product/ProductList.tsx
> +    }, [categoryNo]);
아뇨 생각을 잘못한거 같습니다 수정하겠습니다

2022-06-29 08:30 UTC, LeeYhunHwan commented on src/pages/Product/ProductList.tsx
> +                categoryNos: secondaryCategory?.toString(),
모든 categoryNo(categoryNo, state로 다룰 categoryNo)는 string이었는데 굳이 할 필요가 없었네요 제가 실수 한 것  같습니다.

2022-07-01 08:52 UTC, jerome-geek requested changes

2022-07-01 08:52 UTC, jerome-geek commented on src/pages/Product/ProductList.tsx
>      const { categoryNo } = useParams() as { categoryNo: string };
`useParams` 타입 정의를 보고 as를 제거해주세요

2022-07-01 08:52 UTC, jerome-geek commented on src/pages/Product/ProductList.tsx
> +    const [currentCategoryNo, setCurrentCategoryNo] = useState(categoryNo);
여긴 타입을 명시해주는게 조금 더 명확한 코드가 되겠네요

2022-07-01 08:52 UTC, jerome-geek commented on src/pages/Product/ProductList.tsx
> +                categoryNos: currentCategoryNo?.toString(),
여기도 위에 state에서 타입을 명시해주면 `toString` method는 지워도 되겠네요

2022-07-01 08:53 UTC, jerome-geek commented
배열의 첫번째 값을 사용할때는 index로 접근하기보다 `head` 함수를 사용해주시면 좋을 것 같아요

2022-07-06 14:12 UTC, jerome-geek approved these changes

2022-07-06 14:14 UTC, merged