ProductDetail Page 작성
jerome-geek/reactjs-starter pull request #52
Opened 2022-07-06 03:12 UTC by LeeYhunHwan

2022-07-06 14:35 UTC, jerome-geek requested changes
상품 상세 페이지에서는 회원 / 비회원 나눠서 액션이 들어가야합니다.
내일 출근하시면 두레이에 회원 / 비회원으로 나눠서 상품 상세 페이지에서는 어떤 액션이 들어갈 수 있는지 먼저 정리해주세요

2022-07-06 14:35 UTC, jerome-geek commented on src/api/order/cart.ts
>          }),
post요청에서는 data -> body로 바꿔주세요

2022-07-06 14:35 UTC, jerome-geek commented on src/api/product/product.ts
> +
API에 해당하는 주석은 제가 작성한 것을 보고 작성해주세요, 
`hasOptionValues: data.hasOptionValues ? data.hasOptionValues : true` 파라미터에 이미 boolean이라고 명시가 되어있는데, 이 부분은 왜 이렇게 쓰셨을까요?

2022-07-06 14:35 UTC, jerome-geek commented on src/pages/Product/ProductDetail.tsx
> +    const [optionProduct, setOptionProduct] = useState(
여기서 자료형으로 Map을 쓰신 이유가 있을까요?

2022-07-06 14:35 UTC, jerome-geek commented on src/pages/Product/ProductDetail.tsx
> +        Array.from(optionProduct.values()).forEach((ele) => {
ele는 의미없는 변수명이라 지양해야할 변수명이에요

2022-07-06 14:35 UTC, jerome-geek commented on src/pages/Product/ProductDetail.tsx
> +                        {productImageList?.map((element) => {
여기서 element는 의미없는 변수명인 것 같네요

2022-07-08 02:35 UTC, LeeYhunHwan commented on src/pages/Product/ProductDetail.tsx
> +        Array.from(optionProduct.values()).forEach((ele) => {
알겠습니다.

2022-07-08 02:36 UTC, LeeYhunHwan commented on src/api/product/product.ts
> +
잘못 작성했습니다. 주석과 해당 api를 수정하겠습니다.

2022-07-18 03:20 UTC, jerome-geek approved these changes

2022-07-18 03:20 UTC, merged