Refactory/component/product image list
jerome-geek/reactjs-starter pull request #54
Opened 2022-07-18 09:00 UTC by LeeYhunHwan

2022-07-20 09:42 UTC, jerome-geek requested changes
ProductImageList라는 Component는 상품 이미지마 보여주는 단일 역할을 하는 Component인가요?
만약 아니라면 Component 명이 잘못된 것 같네요
props도 너무 한정적인 props만 받아오는데, 이러면 특정 기능에 종속되는 Component가 되겠네요

2022-07-20 09:42 UTC, jerome-geek commented on src/pages/Product/ProductDetail.tsx
> +        useState<number | string>('represent');
currentOptionNo 타입은 초기값이 string인데 string 또는 number가 될 수 있나요?

2022-07-20 09:42 UTC, jerome-geek commented on src/pages/Product/ProductDetail.tsx
>                      return prev;
함수형으로 업데이트할때는 직접 값을 변경하는 방식은 지양해주세요

2022-07-21 00:30 UTC, LeeYhunHwan commented on src/pages/Product/ProductDetail.tsx
>                      return prev;
네 알겠습니다

2022-07-21 00:31 UTC, LeeYhunHwan commented on src/pages/Product/ProductDetail.tsx
> +        useState<number | string>('represent');
생각해보니 string만 들어오겠네요 수정하겠습니다.

2022-07-26 00:57 UTC, jerome-geek approved these changes

2022-07-26 00:58 UTC, merged