SelectBox, SelectBox.stories 작성
jerome-geek/reactjs-starter pull request #55
Opened 2022-07-20 01:45 UTC by LeeYhunHwan

react-select 를 사용하여 SelectBox component 및 SelectBox.stories 를 작성했습니다.
작성한 SelectBox를 사용하여 ProductOptionList 컴포넌트를 리팩토링 했습니다.

2022-07-20 09:38 UTC, jerome-geek requested changes

2022-07-20 09:38 UTC, jerome-geek commented on src/components/Common/SelectBox.stories.tsx
> +);
해당 Component가 받는 props는 options, onChange, styles라고 작성하셨는데 storybook에서는 해당 값을 밖에서 주입하신 이유가 뭘까요?
실제로 컴포넌트가 쓰이는 것과 같이 props를 사용해야하지 않을까요?

2022-07-20 09:38 UTC, jerome-geek commented on src/components/Common/SelectBox.stories.tsx
> +};
해당 props는 케이스별 args에 넣어주세요

2022-07-20 09:38 UTC, jerome-geek commented on src/components/Common/SelectBox.tsx
> +    };
`Partial<FlatOption>`이라는 타입에 종속적인 컴포넌트가 되기 때문에 Partial<FlatOption>은 generic으로 받으면 되겠네요
styles는 width만 수정이 가능한가요?

2022-07-20 09:38 UTC, jerome-geek commented on src/components/Common/SelectBox.tsx
> +                container: (provided: any) => ({
provided 는 왜 any타입으로 사용하셨을까요?

2022-07-20 09:38 UTC, jerome-geek commented on src/components/Common/SelectBox.tsx
> +            placeholder={'제품을 선택해주세요'}
이 컴포넌트는 제품만 선택할 수 있는 컴포넌트 인가요?

2022-07-20 09:38 UTC, jerome-geek commented on src/pages/Product/ProductDetail.tsx
>                      return prev;
객체의 값을 직접 접근해서 수정하는 것은 함수형으로 업데이트할 경우에 지양해야 하는 방법입니다

2022-07-20 09:38 UTC, jerome-geek commented on src/components/Product/ProductOptionList.tsx
> +import { SingleValue } from 'react-select';
library는 상단에 위치시켜주세요

2022-07-21 00:57 UTC, LeeYhunHwan commented on src/components/Common/SelectBox.tsx
> +            placeholder={'제품을 선택해주세요'}
props로 따로 빼놓겠습니다

2022-07-21 00:57 UTC, LeeYhunHwan commented on src/pages/Product/ProductDetail.tsx
>                      return prev;
넵

2022-07-21 00:57 UTC, LeeYhunHwan commented on src/components/Product/ProductOptionList.tsx
> +import { SingleValue } from 'react-select';
알겠습니다

2022-07-21 00:58 UTC, LeeYhunHwan commented on src/components/Common/SelectBox.tsx
> +                container: (provided: any) => ({
첫 번째 인자값은 기존의 style인데 정확히 무엇인지 파악되지 않아 any를 사용했습니다.

2022-07-26 00:58 UTC, jerome-geek approved these changes

2022-07-26 00:58 UTC, merged