:sparkles: feat: shopAPI > mange > address, board API 작성
jerome-geek/reactjs-starter pull request #8
Opened 2022-05-11 02:04 UTC by LeeYhunHwan

## address
- 주소 조회하기 (searchAddress)
- 게시판 설정 조회하기 (getConfigs)
- 게시글 리스트 조회하기 (getArticlesByBoardId)
- 게시글 작성하기 (postArticle)
- 게시판 카테고리 목록 조회하기 (getCategories)
- 게시글 상세 조회하기 (getArticleDetail)
- 게시글 수정하기 (updateArticle)
- 게시글 삭제하기 (deleteArticle)
- 게시글 수정가능 여부 확인하기 (checkEditableArticle)
- 게시글 추천 (recommendArticle)
- 게시글 추천 취소 (cancelArticleRecommend)

## board

2022-05-12 08:04 UTC, jerome-geek requested changes

2022-05-12 08:04 UTC, jerome-geek commented on src/api/manage/board.ts
> +import { defaultHeaders } from 'api/core';
한줄로 작성해주시는게 좋겠죠?

2022-05-12 08:04 UTC, jerome-geek commented on src/api/manage/board.ts
> +    postArticle: (
게시글 **작성하기** 인데 post는 알맞지 않겠죠?

2022-05-12 08:04 UTC, jerome-geek commented on src/api/manage/board.ts
> +    getArticlesByBoardId: (
함수명에 boardId라고 쓰신 이유가 있을까요? 파라미터명과 일치시켜주는게 더 통일감이 있을 것 같아요

2022-05-13 02:42 UTC, jerome-geek commented
@LeeYhunHwan `yarn.lock` 파일은 왜 올리신걸까요?

2022-05-13 02:42 UTC, jerome-geek requested changes

2022-05-13 02:42 UTC, jerome-geek commented on src/api/manage/board.ts
> +    createArticle: (
@LeeYhunHwan 작성하기는 create보다 write 동사를 써주는게 더 구체적일듯 싶은데 어떻게 생각하시나요?

2022-05-13 07:52 UTC, LeeYhunHwan commented on src/api/manage/board.ts
> +    createArticle: (
막연하게 CRUD 를 생각했는데 혹시 게시글이라서 write가 더 구체적이겠네요 수정하겠습니다.

2022-05-16 01:22 UTC, merged